name: notiva
description: A smart, cross-platform note-taking app built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: ^9.2.1

  # Routing
  go_router: ^17.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  
  assets:
    - shorebird.yaml
