// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkN8UEWRd8KHeJLFJdoT6FufwyAjRGHIM',
    appId: '1:673380585179:web:547009a4dca39e28c486fe',
    messagingSenderId: '673380585179',
    projectId: 'notiva-f1114',
    authDomain: 'notiva-f1114.firebaseapp.com',
    storageBucket: 'notiva-f1114.firebasestorage.app',
    measurementId: 'G-1NPN9ET9X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7nthBIP5QcWZyTN3XW_GZOweT4-Lu2c',
    appId: '1:673380585179:android:4bc868bde31d1d27c486fe',
    messagingSenderId: '673380585179',
    projectId: 'notiva-f1114',
    storageBucket: 'notiva-f1114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCpVzheVwmFbCWeECCXz5tpnENV7ev_4',
    appId: '1:673380585179:ios:ea93cb0828ddd91bc486fe',
    messagingSenderId: '673380585179',
    projectId: 'notiva-f1114',
    storageBucket: 'notiva-f1114.firebasestorage.app',
    iosBundleId: 'com.korya.notiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCpVzheVwmFbCWeECCXz5tpnENV7ev_4',
    appId: '1:673380585179:ios:ea93cb0828ddd91bc486fe',
    messagingSenderId: '673380585179',
    projectId: 'notiva-f1114',
    storageBucket: 'notiva-f1114.firebasestorage.app',
    iosBundleId: 'com.korya.notiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkN8UEWRd8KHeJLFJdoT6FufwyAjRGHIM',
    appId: '1:673380585179:web:57ce0a401712c175c486fe',
    messagingSenderId: '673380585179',
    projectId: 'notiva-f1114',
    authDomain: 'notiva-f1114.firebaseapp.com',
    storageBucket: 'notiva-f1114.firebasestorage.app',
    measurementId: 'G-G7MP8HMEPQ',
  );
}
